
set_property PACKAGE_PIN P1 [get_ports {o_led[0]}]
set_property PACKAGE_PIN N2 [get_ports {o_led[1]}]
set_property PACKAGE_PIN M2 [get_ports {o_led[2]}]
set_property PACKAGE_PIN L2 [get_ports {o_led[3]}]
set_property PACKAGE_PIN J1 [get_ports {o_led[4]}]
set_property PACKAGE_PIN H2 [get_ports {o_led[5]}]
set_property PACKAGE_PIN L4 [get_ports {o_led[6]}]
set_property PACKAGE_PIN L3 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports o_led*]

set_property PACKAGE_PIN J3 [get_ports clk25mhz]
set_property IOSTANDARD LVCMOS18 [get_ports clk25mhz]

set_property PACKAGE_PIN E4 [get_ports {o8_segc[7]}]
set_property PACKAGE_PIN D3 [get_ports {o8_segc[6]}]
set_property PACKAGE_PIN N5 [get_ports {o8_segc[5]}]
set_property PACKAGE_PIN P5 [get_ports {o8_segc[4]}]
set_property PACKAGE_PIN N4 [get_ports {o8_segc[3]}]
set_property PACKAGE_PIN C3 [get_ports {o8_segc[2]}]
set_property PACKAGE_PIN R5 [get_ports {o8_segc[1]}]
set_property PACKAGE_PIN N3 [get_ports {o8_segc[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports o8_segc*]

set_property PACKAGE_PIN A8 [get_ports {o5_sega[0]}]
set_property PACKAGE_PIN A9 [get_ports {o5_sega[1]}]
set_property PACKAGE_PIN B9 [get_ports {o5_sega[2]}]
set_property PACKAGE_PIN A7 [get_ports {o5_sega[3]}]
set_property PACKAGE_PIN B6 [get_ports {o5_sega[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports o5_sega*]
